# -*- coding: utf-8 -*-
"""PrakAlgo10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17m0yF6c6xG4vI8Zk4dJGHO2wKhS7WnIT
"""

data = {}

def input_data():
    nama = input("Masukkan nama mahasiswa: ")
    praktikum1 = int(input("Masukkan nilai praktikum 1: "))
    praktikum2 = int(input("Masukkan nilai praktikum 2: "))
    praktikum3 = int(input("Masukkan nilai praktikum 3: "))

    data[nama] = {'Praktikum 1': praktikum1, 'Praktikum 2': praktikum2, 'Praktikum 3': praktikum3}
    print(f"Data mahasiswa {nama} berhasil dimasukkan.")

def view_data():
    print("NAMA    | PRAK 1 | PRAK 2 | PRAK 3")
    for nama, nilai in data.items():
        print(f"{nama:8} | {nilai['Praktikum 1']:6} | {nilai['Praktikum 2']:6} | {nilai['Praktikum 3']:6}")

def hitung_rata_rata_mahasiswa():
    print("[3. HITUNG RATA-RATA PRAK TIAP MAHASISWA]")
    for nama, nilai in data.items():
        rata_rata = sum(nilai.values()) / len(nilai)
        print(f"{nama} = {rata_rata}")

def hitung_rata_rata_praktikum():
    print("[4. HITUNG RATA-RATA TIAP PRAK]")
    for i in range(1, 4):
        rata_rata_prak = sum(nilai[f'Praktikum {i}'] for nilai in data.values()) / len(data)
        print(f"Rerata Prak {i} = {rata_rata_prak}")

def mencari_rata_rata_mahasiswa():
    nama = input("Masukkan nama mahasiswa: ")
    if nama in data:
        rata_rata = sum(data[nama].values()) / len(data[nama])
        print(f"Rerata nilai praktikum {nama} = {rata_rata}")
    else:
        print(f"Mahasiswa dengan nama {nama} tidak ditemukan.")

def update_nilai_praktikum():
    nama = input("Masukkan nama mahasiswa: ")
    if nama in data:
        praktikum_ke = int(input("Ingin update nilai praktikum ke-: "))
        if praktikum_ke in [1, 2, 3]:
            nilai_baru = int(input("Nilai baru: "))
            data[nama][f'Praktikum {praktikum_ke}'] = nilai_baru
            print(f"Nilai praktikum {praktikum_ke} mahasiswa {nama} berhasil diupdate.")
        else:
            print("Nomor praktikum tidak valid.")
    else:
        print(f"Mahasiswa dengan nama {nama} tidak ditemukan.")

# Main program loop
while True:
    print("\nPROGRAM LIST")
    print("1. Input Data")
    print("2. View Data")
    print("3. Hitung Nilai Rata-Rata Praktikum Tiap Mahasiswa")
    print("4. Hitung Nilai Rata-Rata Tiap Praktikum")
    print("5. Mencari Nilai Rata-Rata Praktikum Mahasiswa")
    print("6. Update Nilai Praktikum Mahasiswa")
    print("7. Exit")

    pilihan = input("Pilih menu yang tersedia: ")

    if pilihan == '1':
        input_data()
    elif pilihan == '2':
        view_data()
    elif pilihan == '3':
        hitung_rata_rata_mahasiswa()
    elif pilihan == '4':
        hitung_rata_rata_praktikum()
    elif pilihan == '5':
        mencari_rata_rata_mahasiswa()
    elif pilihan == '6':
        update_nilai_praktikum()
    elif pilihan == '7':
        print("TERIMA KASIH CUYYY!!!")
        break
    else:
        print("Pilihan tidak valid. Silakan pilih menu yang tersedia.")